Updates

diff --git a/bash_extensions b/bash_extensions
--- a/bash_extensions
+++ b/bash_extensions
@@ -10,6 +10,8 @@
 # OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 # WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 
+set -eo pipefail
+
 
 ###############################################################################
 # Basics
@@ -19,11 +21,11 @@
 export HISTCONTROL=ignoredups:erasedups  # no duplicate entries
 export HISTSIZE=1000000                  # big big history
 export HISTFILESIZE=1000000              # big big history
-shopt -s histappend                      # append to history, don't overwrite it
+# shopt -s histappend                      # append to history, don't overwrite it
 
 # fixes https://github.com/asdf-vm/asdf/issues/279#issue-290858023
 # and possibly other issues:
-touch $HOME/.bash_sessions_disable
+# touch $HOME/.bash_sessions_disable
 
 ulimit -n 1024
 
@@ -47,17 +49,27 @@ function ga {
   alias | grep "$1" | grep -v grep
 }
 
-alias ebp='$EDITOR ~/.bash_profile'
-alias ebpe='$EDITOR ~/.dev_env'
-alias sbp='. ~/.bash_profile'
+alias ezsh='$EDITOR ~/.zshrc'
+alias ezshe='$EDITOR ~/.dev_env'
+alias szsh='. ~/.zshrc'
 
 # remove all .svn dirs in the current dir and subdirs
 alias rmsvn='find . -name ".svn" -exec rm -rf "{}" \;'
 alias rmds='find . -name ".DS_Store" -exec rm -rf "{}" \;'
 
+alias rsink='rsync --archive --compress --verbose --progress --human-readable'
+alias rsinkd='rsink --delete'
+
+alias pg='ping www.google.com'
+
 # eg "psg mysql" to see all mysql processes
 function psg {
   ps wwwaux | egrep "($1|%CPU)" | grep -v grep
+}
+
+# eg "port 3000" to see what is running there
+function port {
+  lsof -i -n -P | grep TCP | grep "$1"
 }
 
 # Display folder and it's content as a tree
@@ -65,63 +77,20 @@ function tree {
   find ${1:-.} -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'
 }
 
-# GIT & prompt
+# GIT
 
 alias g=git
-alias grc='git rebase --continue'
-alias wip='git commit -m WIP .'
+alias wip='git commit -m WIP'
 
 export GIT_DUET_CO_AUTHORED_BY=1
 
-# parse_git_branch() {
-#   git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ [\1]/'
-# }
-
-# if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
-#   host="\[\e[01;35m\]\u@\h\[\e[0m\]"
-# else
-#   host="\[\e[01;30m\]\h\[\e[0m\]"
-# fi
-
-# # from https://stackoverflow.com/a/3499237/1533892
-# _dir_chomp () {
-#     local p=${1/#$HOME/\~} b s
-#     s=${#p}
-#     while [[ $p != "${p//\/}" ]]&&(($s>$2))
-#     do
-#         p=${p#/}
-#         [[ $p =~ \.?. ]]
-#         b=$b/${BASH_REMATCH[0]}
-#         p=${p#*/}
-#         ((s=${#b}+${#p}))
-#     done
-#     echo ${b/\/~/\~}${b+/}$p
-# }
-
-# export PS1='\[\e[01;30m\]\h\[\e[0m\] $( _dir_chomp "$(pwd)" 20 )\[\e[01;32m\]$(parse_git_branch)\[\e[01;30m\] \$\[\033[00m\] '
-
-# export PS1="\w\[\e[01;32m\]\$(parse_git_branch)\[\e[0m\]\[\e[1;36m\] $ \[\e[0m\]"
-
-# export PS1='$(eval "sps")$ '
-# sps() {
-#    echo "$PWD" | gsed -r 's|/([^/]{,2})[^/]*|/\1|g'
-# }
-
-# This prompt setup requires:
-# brew install bash-completion
-[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
-[[ -r "/usr/local/opt/git/etc/bash_completion.d/git-prompt.sh" ]] && . "/usr/local/opt/git/etc/bash_completion.d/git-prompt.sh"
-export GIT_PS1_SHOWDIRTYSTATE=true
-export GIT_PS1_SHOWCOLORHINTS=1
-export PROMPT_COMMAND='__git_ps1 "\W" "\\\$ "'
-export PROMPT_COMMAND='__git_ps1 "\w" "\[\e[0m\]\[\e[1;36m\] $ \[\e[0m\]"'
-# export PS1="\w\[\e[01;32m\]\$(parse_git_branch)\[\e[0m\]\[\e[1;36m\] $ \[\e[0m\]"
-
-
-alias rsink='rsync --archive --compress --verbose --progress --human-readable'
-alias rsinkd='rsink --delete'
-
-alias pg='ping www.google.com'
+# [[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
+# [[ -r "/usr/local/opt/git/etc/bash_completion.d/git-prompt.sh" ]] && . "/usr/local/opt/git/etc/bash_completion.d/git-prompt.sh"
+# export DISABLE_UNTRACKED_FILES_DIRTY=false
+# export GIT_PS1_SHOWDIRTYSTATE=true
+# export GIT_PS1_SHOWCOLORHINTS=1
+# export PROMPT_COMMAND='__git_ps1 "\W" "\\\$ "'
+# export PROMPT_COMMAND='__git_ps1 "\w" "\[\e[0m\]\[\e[1;36m\] $ \[\e[0m\]"'
 
 ###############################################################################
 # AWS
@@ -156,20 +125,12 @@ if [ $OSTYPE != 'linux-gnu' ]; then
   export EDITOR='code'
   alias vs=code
 
-  #   alias toatom='tmpin atom'
-  #
-  #   # requires `npm install --global tmpin`
-  #   function gda {
-  #     git diff $1 | toatom
-  #   }
-
   # For homebrew-based mysql install:
   alias mystop='/usr/local/opt/mysql56/bin/mysql.server stop'  #  ; killall mysqld'
   alias mystart='/usr/local/opt/mysql56/bin/mysql.server start'
 
   alias camera='sudo killall VDCAssistant'
   # if that fails, add or try: sudo killall AppleCameraAssistant
-
 fi
 
 ###############################################################################
@@ -206,7 +167,7 @@ function yad {
 
 alias nbump='npm version patch'
 alias npub='npm version patch && git push --tags origin HEAD && npm publish'
-alias nup='ncu --upgrade --upgradeAll && npm update && npm prune'  # npm i -g npm-check-updates
+# alias nup='ncu --upgrade && npm update && npm prune'  # if this fails:  `npm upgrade -g npm-check-updates`
 alias n='npm'
 alias nt='npm test'
 alias nr='npm run'
@@ -232,14 +193,6 @@ function nv {
 
 # rbenv:
 eval "$(rbenv init -)"
-
-# RVM  -- WE NEED TO DO THIS LAST(ISH); GETS THINGY IF IT'S NOT ABLE TO CLAIM FIRST ENTRY IN PATH
-# export PATH="$HOME/.rvm/bin:$PATH:$HOME/.rvm/bin"
-# [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
-
-# citizen-scripts gem
-
-alias c='biq && be citizen'
 
 # Bundler
 
@@ -273,12 +226,12 @@ alias rds='br db:seed'
 
 alias ss='spring stop'
 
-###############################################################################
-# asdf
-###############################################################################
+# ###############################################################################
+# # asdf
+# ###############################################################################
 
-. $HOME/.asdf/asdf.sh
-. $HOME/.asdf/completions/asdf.bash
+# . $HOME/.asdf/asdf.sh
+# . $HOME/.asdf/completions/asdf.bash
 
 ###############################################################################
 # Other
@@ -297,11 +250,9 @@ export PATH=/usr/local/opt/postgresql\@10/bin:$PATH
 #alias tomcat-shutdown='/usr/local/Cellar/tomcat6/6.0.45/bin/shutdown.sh'
 #alias tomcat-stop='/usr/local/Cellar/tomcat6/6.0.45/bin/shutdown.sh'
 
-if [ $OSTYPE == 'linux-gnu' ]; then
+if [ $OSTYPE = 'linux-gnu' ]; then
   export EDITOR=`which nano`
 fi
-
-alias si='[[ -s bin/shipit ]] && bin/shipit || yarn run shipit'
 
 # This echoes a bunch of color codes to the terminal to demonstrate
 # what's available. Each line is the color code of one forground color,
